# -*- coding: utf-8 -*-
"""edge_in4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EP9LmG-FoZHAhH4BOg8KU2w7dwYFNVae
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.utils import to_categorical

# 1. Load MNIST dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# 2. Preprocess data
x_train = x_train / 255.0
x_test = x_test / 255.0

x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# 3. Build CNN model
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D((2,2)),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D((2,2)),

    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# 4. Compile model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# 5. Train model
model.fit(x_train, y_train, epochs=5, batch_size=64)

# 6. Evaluate model
loss, accuracy = model.evaluate(x_test, y_test)
print("Test Accuracy:", accuracy)

import pickle

# Save model architecture (config)
model_config = model.to_json()

# Save model weights
model_weights = model.get_weights()

with open("cnn_model.pkl", "wb") as f:
    pickle.dump((model_config, model_weights), f)

print("Model saved using pickle")

import pickle
from tensorflow.keras.models import model_from_json

with open("cnn_model.pkl", "rb") as f:
    model_config, model_weights = pickle.load(f)

# Rebuild model
loaded_model = model_from_json(model_config)
loaded_model.set_weights(model_weights)

# Compile again
loaded_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("Model loaded successfully")